### ISSUE TITLE
Not GNU/Linux ;)

### ISSUE THREAD

**Issue by 0xDarkSky** [pinokaille/ShiborOS#2]
"I use Winyux as my opewating system," I state pwoudwy woudwy to the unkempt, beawded man. He swivews awound in his desk chaiw with a d-d-deviwish gweam in his eyes, weady to manspwain with e-extweme pwecision. "Actuawwy Wuawwy", he says w-w-with a gwin, "Winyux is just the k-kewnyew. You use GNYU+Winyux!' I don't miss a beat and wepwy with a smiwk, "I use Awpinye, a distwo that doesn't incwude the G-GNYU Coweutiws, ow any othew GNYU code. I-It's Winyux, but it's nyot GNYU+Winyux." The s-smiwe quickwy wuickwy d-d-d-dwops fwom the man's face. His body begins convuwsing and he foams at the mouth and dwops to t-the fwoow with a sickwy wickwy thud. As he wwithes awound he scweams "I-IT WAS COMPIWED WITH GCC! THAT M-MEANS IT'S STIWW GNYU!" Coowwy Woowwy, I wepwy "If windows w-wewe compiwed with G-GCC, wouwd that make it GNYU?" I intewwupt his wesponse with "-and wowk is being made on the kewnyew to make it mowe compiwew-agnyostic. Even if you wewe cowwect, you won't be f-fow wong." With a sickwy wickwy wheeze, the wast of the man's wife is ejected fwom his body. He wies on the fwoow, cowd and wimp. I've womanspwainyed him to death.

**Comment by pinokaille** [comment]
tg
